import { Property } from './types';

export const properties: Property[] = [
  {
    squareFootage: 1500,
    lighting: 'medium',
    price: 300000,
    rooms: 3,
    bathrooms: 2,
    location: [40.7128, -74.0060],
    description: 'Beautiful property with modern amenities.',
    ammenities: { yard: true, garage: false, pool: true },
  },
  {
    squareFootage: 2000,
    lighting: 'high',
    price: 450000,
    rooms: 4,
    bathrooms: 3,
    location: [34.0522, -118.2437],
    description: 'Spacious home in a great location.',
    ammenities: { yard: true, garage: true, pool: false },
  },
  {
    squareFootage: 1000,
    lighting: 'low',
    price: 200000,
    rooms: 2,
    bathrooms: 1,
    location: [41.8781, -87.6298],
    description: 'Cozy home with easy access to public transport.',
    ammenities: { yard: false, garage: false, pool: false },
  },
  {
    squareFootage: 2500,
    lighting: 'high',
    price: 750000,
    rooms: 5,
    bathrooms: 4,
    location: [29.7604, -95.3698],
    description: 'Luxurious property with plenty of space for the whole family.',
    ammenities: { yard: true, garage: true, pool: true },
  },
  {
    squareFootage: 1200,
    lighting: 'medium',
    price: 280000,
    rooms: 3,
    bathrooms: 2,
    location: [33.7490, -84.3880],
    description: 'Affordable family home with great schools nearby.',
    ammenities: { yard: true, garage: false, pool: false },
  },
  {
    squareFootage: 800,
    lighting: 'low',
    price: 150000,
    rooms: 1,
    bathrooms: 1,
    location: [47.6062, -122.3321],
    description: 'Compact apartment ideal for single professionals.',
    ammenities: { yard: false, garage: false, pool: false },
  },
  {
    squareFootage: 1800,
    lighting: 'medium',
    price: 400000,
    rooms: 3,
    bathrooms: 2.5,
    location: [39.7392, -104.9903],
    description: 'Modern home with stunning mountain views.',
    ammenities: { yard: true, garage: true, pool: false },
  },
  {
    squareFootage: 3000,
    lighting: 'high',
    price: 950000,
    rooms: 6,
    bathrooms: 5,
    location: [25.7617, -80.1918],
    description: 'Exclusive waterfront property with private pool.',
    ammenities: { yard: true, garage: true, pool: true },
  },
  {
    squareFootage: 1600,
    lighting: 'medium',
    price: 320000,
    rooms: 3,
    bathrooms: 2,
    location: [38.9072, -77.0369],
    description: 'Townhome with easy access to city amenities.',
    ammenities: { yard: false, garage: true, pool: false },
  },
  {
    squareFootage: 900,
    lighting: 'low',
    price: 180000,
    rooms: 2,
    bathrooms: 1,
    location: [36.1627, -86.7816],
    description: 'Charming cottage with a rustic feel.',
    ammenities: { yard: true, garage: false, pool: false },
  },
  {
    squareFootage: 2200,
    lighting: 'high',
    price: 500000,
    rooms: 4,
    bathrooms: 3,
    location: [32.7767, -96.7970],
    description: 'Family-friendly home in a quiet suburban neighborhood.',
    ammenities: { yard: true, garage: true, pool: false },
  },
  {
    squareFootage: 2600,
    lighting: 'high',
    price: 850000,
    rooms: 5,
    bathrooms: 4,
    location: [37.7749, -122.4194],
    description: 'Premium property with breathtaking city views.',
    ammenities: { yard: false, garage: true, pool: false },
  },
];
